version: 2
updates:
  - package-ecosystem: "gradle"       # Specify Maven as the package manager
    directory: "/"                  # Root directory where the `pom.xml` file exists
    schedule:
      interval: "weekly"   
